### ISSUE TITLE
Issuing modded items as rewards / using item ID?

### ISSUE THREAD

**Issue by krisjenner** [UpcraftLP/Votifier#4]
Is there a way to use an item ID instead of name to issue rewards? Whenever I try to set it to anything non-vanilla, I don't receive the reward.

**Comment by UpcraftLP** [comment]
simply put: no. IDs change between installation, or even different worlds, whereas registry names do not.
can you show your config that does not work, maybe?

**Comment by UpcraftLP** [comment]
closed due to inactivity
